formatting, style, misc changes, and fixes

diff --git a/backup-meta b/backup-meta
--- a/backup-meta
+++ b/backup-meta
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-#2.0.2
-#2019-04-04
+#2.1.0
+#2019-05-17
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -16,6 +16,8 @@
 #
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }
 
 finish() { if [ -d "${tmpdir}" ];then rm --preserve-root -r "${tmpdir}";fi }
 trap 'exit 1' INT HUP QUIT TERM USR1
@@ -35,34 +37,32 @@ move_finish(){
 	mv -iv "${tmpdir}/${target_comp}" "${target_dest}"
 }
 
-hlp(){
-	printf "\nGENERAL\n"
-	printf " -h\tprint this help\n"
-	printf " -v\tverbose tar\n"
-	printf " -x\tuse xz\n"
-	printf " -z\tuse zstd\n"
-	printf "\nCOMPRESS\n"
-	printf " -1\tchromium\n"
-	printf " -2\thome-bin\n"
-	printf " -3\thome-config\n"
-	printf " -4\thome-local\n"
-	printf " -5\tetc\n"
-	printf " -6\tvnstat\n"
-}
-
 mode="${0##*/backup-}"
 while getopts "123456hvxz" OPT;do
 	case "$OPT" in
 		1) mode="chromium";;
-		2) mode="home-bin";;
-		3) mode="home-config";;
-		4) mode="home-local";;
+		2) mode="user-bin";;
+		3) mode="user-config";;
+		4) mode="user-local";;
 		5) mode="etc";;
 		6) mode="vnstat";;
 		v) V="v";;
 		x) comp="xz";;
 		z) comp="zstd";;
-		h) hlp;exit;;
+		h)
+			printf "\nGENERAL\n"
+			printf " -h\tprint this help\n"
+			printf " -v\tverbose tar\n"
+			printf " -x\tuse xz\n"
+			printf " -z\tuse zstd\n"
+			printf "\nCOMPRESS\n"
+			printf " -1\tchromium\n"
+			printf " -2\tuser-bin\n"
+			printf " -3\tuser-config\n"
+			printf " -4\tuser-local\n"
+			printf " -5\tetc\n"
+			printf " -6\tvnstat\n"
+			exit;;
 	esac
 done
 
@@ -76,7 +76,7 @@ case "${mode}" in
 		target_source="${HOME}/.config/chrome"
 		target_dest="${backup_dir}/${user}/chromium-profiles/${date}"
 		dir_check
-		cd "${target_source}"
+		cd "${target_source}" || die
 		for f in *chrom*;do
 			target_comp="${date}-${user}-${f}.tar.${E}"
 			tar \
@@ -85,7 +85,18 @@ case "${mode}" in
 			move_finish
 		done
 		;;
-	home-config)
+	user-bin)
+		target_comp="${date}-${user}-bin.tar.${E}"
+		target_source="${HOME}/.bin"
+		target_dest="${backup_dir}/${user}/bin"
+		dir_check
+		mkdir "${tmpdir}"/bin
+		cd "${tmpdir}" || die
+		tar \
+			--xattrs --sparse -${V}cf - "${target_source}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
+		move_finish
+		;;
+	user-config)
 		target_comp="${user}-config-${date}.tar.${E}"
 		target_source="${HOME}/.config"
 		target_dest="${backup_dir}/${user}/config"
@@ -99,7 +110,7 @@ case "${mode}" in
 			--exclude="${target_source}/kernel/distfiles/*" \
 			--xattrs --sparse -${V}cf - "${target_source}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
 		;;
-	home-local)
+	user-local)
 		target_comp="${user}-local-${date}.tar.${E}"
 		target_source="${HOME}/.local"
 		target_dest="${backup_dir}/${user}/local"
@@ -118,19 +129,6 @@ case "${mode}" in
 			--xattrs --sparse -${V}cf - "${target_source}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
 		move_finish
 		;;
-	home-bin)
-		target_comp="${date}-${user}-bin.tar.${E}"
-		target_source="${HOME}/.bin"
-		target_dest="${backup_dir}/${user}/bin"
-		dir_check
-		mkdir "${tmpdir}"/bin
-		cp -r "${target_source}" "${tmpdir}/bin"
-		cd "${tmpdir}"
-		tar \
-			--xattrs --sparse -${V}cf - "${target_source}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
-		rm -rf "${tmpdir}/bin"
-		move_finish
-		;;
 	vnstat)
 		year=$(date "+%Y")
 		month=$(date "+%m")
@@ -140,5 +138,6 @@ case "${mode}" in
 		mkdir -p "${target_dest}/${year}/${month}/${day}"
 		cp "${target_source}" "${target_dest}/${year}/${month}/${day}"
 		;;
-	meta) hlp;exit;;
+	meta) "${0}" -h;exit;;
+	*) printf "Invalid\n"
 esac
diff --git a/image-convert b/image-convert
--- a/image-convert
+++ b/image-convert
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-#5.1.0
-#2019-03-28
+#5.2.0
+#2019-05-17
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -23,18 +23,20 @@
 #acceptable size range
 #rezizing when w > h
 
+die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }
+
 convert_main(){
 	if [ "${batch}" = "1" ];then
 		batch="0"
-		nest_dir=$(find . -mindepth 2 -path '*/*' -type d)
-		if [ -n "${nest_dir}" ];then printf "Nested directories detected\n\n${nest_dir}\n\n";fi
+		nest_dir="$(find . -mindepth 2 -path '*/*' -type d)"
+		if [ -n "${nest_dir}" ];then printf "Nested directories detected\n\n%s\n\n" "${nest_dir}";fi
 		if [ "${mimecheck}" = "1" ];then mime-correct -A;mimecheck="0";fi
 		for d in *;do
 			if [ -d "${d}" ];then
-				cd "${d}"
-				printf "Running in: ${d}\n"
+				cd "${d}" || die
+				printf "Running in: %s\n" "${d}"
 				convert_main "${1}"
-				cd ..
+				cd .. || die
 			fi
 		done
 		exit
@@ -60,12 +62,12 @@ convert_main(){
 					fi
 					if [ "${debug}" = "1" ];then iter="1";fi
 					while true;do
-						if [ "${debug}" = "1" ];then printf "iter ${iter}\n";fi
+						if [ "${debug}" = "1" ];then printf "iter %s\n" "${iter}";fi
 						gm convert -quality ${qual} "${f%%}" "${cvloc}/${f%.*}.${newext}"
 						test_size "${f%%}" "${cvloc}/${f%.*}.${newext}"
 						if [ "${new_smaller}" = "1" ];then
 							new_smaller="0"
-							printf "final qual is ${qual} for ${f}\n"
+							printf "final qual is %s for %s\n" "${qual}" "${f}"
 							mv "${f}" "${O}"
 							break
 						fi
@@ -75,7 +77,7 @@ convert_main(){
 					done
 					;;
 				resize)
-					gm convert ${f%%} -resize "${size}"\> "${cvloc}/${f%%}"
+					gm convert "${f%%}" -resize "${size}"\> "${cvloc}/${f%%}"
 					mv "${f}" "${O}"
 					;;
 				get_size)
@@ -102,7 +104,7 @@ test_size(){
 		echo "filesize orig : $(du ${orig}|awk '{print $1}')"
 	fi
 
-	if [ "$(du ${orig}|awk '{print $1}')" -ge "$(du ${new}|awk '{print $1}')" ];then
+	if [ "$(du "${orig}"|awk '{print $1}')" -ge "$(du "${new}"|awk '{print $1}')" ];then
 		new_smaller="1"
 	fi
 }
@@ -115,44 +117,6 @@ get_mode(){
 	fi
 }
 
-hlp(){
-	printf "GENERAL\n"
-	printf " -d\textra printouts\n"
-	printf " -m\tdisable mime check\n"
-	printf " -r\tdo not keep orig\n"
-	printf " -s\tget current image size in dir\n"
-	printf "\nBATCH\n"
-	printf " example, $0 -B -P 0\n"
-	printf " -B\tbatch, must come before other args\n"
-	printf " -b\tbatch, must come before other args, uses -r\n"
-	printf "\nRESIZE Width, keeps aspect\n"
-	printf " -W *\tuse value provided\n"
-	printf " -W 1\t2400x\n"
-	printf " -W 2\t1600x\n"
-	printf " -W 3\t1280x\n"
-	printf " -W 4\t980x\n"
-	printf " -W 5\t780x\n"
-	printf "\nRESIZE Hight, keeps aspect\n"
-	printf " -H *\tuse value provided, must prefix with 'x'\n"
-	printf " -H 1\tx2400\n"
-	printf " -H 2\tx1600\n"
-	printf " -H 3\tx1280\n"
-	printf " -H 4\tx980\n"
-	printf " -H 5\tx780\n"
-	printf "\nRESIZE Percent\n"
-	printf " -S *\tuse value provided, must append '%%'\n"
-	printf " -S 1\t90%%\n"
-	printf " -S 2\t80%%\n"
-	printf " -S 3\t70%%\n"
-	printf " -S 4\t60%%\n"
-	printf " -S 5\t50%%\n"
-	printf "\nCONVERT\n"
-	printf " -J [1-100]\tjpg > jpg : 100 quality=100 | 1 quality=1 | 0 sets auto mode\n"
-	printf " -j [1-9]  \tjpg > png : 9   quality=9   | 1 quality=1 | 0 sets auto mode\n"
-	printf " -P [1-9]  \tpng > png : 9   qualitl=9   | 1 quality=1 | 0 sets auto mode\n"
-	printf " -p [1-100]\tpng > jpg : 100 quality=100 | 1 quality=1 | 0 sets auto mode\n"
-}
-
 O="orig"
 mode="z"
 batch="0"
@@ -161,35 +125,35 @@ mimecheck="1"
 keep_orig="1"
 new_smaller="0"
 
-if [ -z "${1}" ];then hlp;exit;fi
+if [ -z "${1}" ];then "${0}" -h;exit;fi
 while getopts "dP:p:J:j:H:W:S:hmsBbr" OPT;do
 	case "$OPT" in
 		j)
 			origext="jpg"
 			newext="png"
 			qual="${OPTARG}"
-			if [ "${qual}" -gt "9" ];then printf "exiting because of invalid range: ${OPTARG}\n";exit;fi
+			if [ "${qual}" -gt "9" ];then printf "exiting because of invalid range: %s\n" "${OPTARG}";exit;fi
 			get_mode
 			;;
 		J)
 			origext="jpg"
 			newext="jpg"
 			qual="${OPTARG}"
-			if [ "${qual}" -gt "100" ];then printf "exiting because of invalid range: ${OPTARG}\n";exit;fi
+			if [ "${qual}" -gt "100" ];then printf "exiting because of invalid range: %s\n" "${OPTARG}";exit;fi
 			get_mode
 			;;
 		p)
 			origext="png"
 			newext="jpg"
 			qual="${OPTARG}"
-			if [ "${qual}" -gt "100" ];then printf "exiting because of invalid range: ${OPTARG}\n";exit;fi
+			if [ "${qual}" -gt "100" ];then printf "exiting because of invalid range: %s\n" "${OPTARG}";exit;fi
 			get_mode
 			;;
 		P)
 			origext="png"
 			newext="png"
 			qual="${OPTARG}"
-			if [ "${qual}" -gt "9" ];then printf "exiting because of invalid range: ${OPTARG}\n";exit;fi
+			if [ "${qual}" -gt "9" ];then printf "exiting because of invalid range: %s\n" "${OPTARG}";exit;fi
 			get_mode
 			;;
 		W)
@@ -237,7 +201,43 @@ while getopts "dP:p:J:j:H:W:S:hmsBbr" OPT;do
 		s) act="get_size";;
 		m) mimecheck="0";;
 		d) debug="1";;
-		h) hlp;exit;;
+		h)
+			printf "GENERAL\n"
+			printf " -d\textra printouts\n"
+			printf " -m\tdisable mime check\n"
+			printf " -r\tdo not keep orig\n"
+			printf " -s\tget current image size in dir\n"
+			printf "\nBATCH\n"
+			printf " example, %s -B -P 0\n" "${0}"
+			printf " -B\tbatch, must come before other args\n"
+			printf " -b\tbatch, must come before other args, uses -r\n"
+			printf "\nRESIZE Width, keeps aspect\n"
+			printf " -W *\tuse value provided\n"
+			printf " -W 1\t2400x\n"
+			printf " -W 2\t1600x\n"
+			printf " -W 3\t1280x\n"
+			printf " -W 4\t980x\n"
+			printf " -W 5\t780x\n"
+			printf "\nRESIZE Hight, keeps aspect\n"
+			printf " -H *\tuse value provided, must prefix with 'x'\n"
+			printf " -H 1\tx2400\n"
+			printf " -H 2\tx1600\n"
+			printf " -H 3\tx1280\n"
+			printf " -H 4\tx980\n"
+			printf " -H 5\tx780\n"
+			printf "\nRESIZE Percent\n"
+			printf " -S *\tuse value provided, must append '%%'\n"
+			printf " -S 1\t90%%\n"
+			printf " -S 2\t80%%\n"
+			printf " -S 3\t70%%\n"
+			printf " -S 4\t60%%\n"
+			printf " -S 5\t50%%\n"
+			printf "\nCONVERT\n"
+			printf " -J [1-100]\tjpg > jpg : 100 quality=100 | 1 quality=1 | 0 sets auto mode\n"
+			printf " -j [1-9]  \tjpg > png : 9   quality=9   | 1 quality=1 | 0 sets auto mode\n"
+			printf " -P [1-9]  \tpng > png : 9   qualitl=9   | 1 quality=1 | 0 sets auto mode\n"
+			printf " -p [1-100]\tpng > jpg : 100 quality=100 | 1 quality=1 | 0 sets auto mode\n"
+			exit;;
 	esac
 done
 #shift $((OPTIND - 1))
diff --git a/kernel-build b/kernel-build
--- a/kernel-build
+++ b/kernel-build
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-#2.15.0
-#2019-05-10
+#2.16.0
+#2019-05-17
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -86,11 +86,11 @@ if ! [ -f "${kdir}/.config" ];then
 	fi
 fi
 
-if [ -n "$(grep CONFIG_MODULES=y ${kdir}/.config)" ];then use_modules="1";else use_modules="0";fi
+if [ "$(grep CONFIG_MODULES=y "${kdir}"/.config)" ];then use_modules="1";else use_modules="0";fi
 
-case "$(echo ${kdir##*/}|grep rc)" in
-	*rc*) kver="$(echo ${kdir##*/linux-}|sed s'/.$//')";;
-	*) kver="$(echo ${kdir##*/linux-}|awk 'BEGIN{FS=OFS="."} NF--')";;
+case "$(echo "${kdir##*/}"|grep rc)" in
+	*rc*) kver="$(echo "${kdir##*/linux-}"|sed s'/.$//')";;
+	*) kver="$(echo "${kdir##*/linux-}"|awk 'BEGIN{FS=OFS="."} NF--')";;
 esac
 
 switch_kconf="${storage}/config/${kver}-config"
@@ -141,8 +141,8 @@ done
 #which are not needed at runtime if zfs is build into the kernel.
 while [ "${run_kernel_bump}" = "1" ];do
 	if ! [ -f "${switch_kconf}" ];then cp "${kdir}/.config" "${switch_kconf}";fi
-	c1=$(grep -s CONFIG_MODULES=y ${switch_kconf})
-	c2=$(grep -s CONFIG_KALLSYMS=y ${switch_kconf})
+	c1=$(grep -s CONFIG_MODULES=y "${switch_kconf}")
+	c2=$(grep -s CONFIG_KALLSYMS=y "${switch_kconf}")
 	if [ "${run_zfs_build}" = "1" ] && [ -z "${c1}" ] || [ -z "${c2}" ];then
 		printf "\nRequired option[s] located at:\n"
 		if [ -z "${c1}" ];then printf "\n[*] Enable loadable module support\n";fi
@@ -169,11 +169,11 @@ case "${use_zfs_version}" in
 		kmod="zfs-kmod" #build path
 		;;
 	release)
-		Z=$(ls -1A --ignore=*9999* ${port}/sys-fs/zfs|sort -V|tail -n1)
-		zver=$(echo ${Z%%.ebuild}|awk '{print $NF}' FS=-) #clean up filename
+		Z="$(ls -1A --ignore=*9999* "${port}"/sys-fs/zfs|sort -V|tail -n1)"
+		zver="$(echo "${Z%%.ebuild}"|awk '{print $NF}' FS=-)" #clean up filename
 		unset Z
 		kmod="zfs" #build path
-		if [ "${use_distdir}" = "0" ];then export DISTDIR="${storage}/distfiles";fi #keep sources on eclean-dist
+		if [ "${use_distdir}" = "0" ];then export DISTDIR="${storage}"/distfiles;fi #keep sources on eclean-dist
 		;;
 esac
 
@@ -187,19 +187,19 @@ if ! [ -d "${kmod_src}" ] && [ "${run_zfs_build}" = "1" ];then run_kmod_build="1
 
 if [ "${run_intro}" = "1" ];then
 	printf "\n"
-	printf "kernel             : ${kdir}\n"
-	printf "Install Kernel     : ${run_kernel_install}\n"
-	printf "ZFS version        : ${zver}\n"
-	printf "ZFS local ebuild   : ${use_local_zfs_ebuild}\n"
-	printf "Configure kmod     : ${run_kmod_build}\n"
-	printf "Enable modules     : ${use_modules}\n"
-	printf "Running emerge     : ${run_emerge}\n"
+	printf "kernel             : %s\n" "${kdir}"
+	printf "Install Kernel     : %s\n" "${run_kernel_install}"
+	printf "ZFS version        : %s\n" "${zver}"
+	printf "ZFS local ebuild   : %s\n" "${use_local_zfs_ebuild}"
+	printf "Configure kmod     : %s\n" "${run_kmod_build}"
+	printf "Enable modules     : %s\n" "${use_modules}"
+	printf "Running emerge     : %s\n" "${run_emerge}"
 	if [ "${intro_extra}" = "1" ];then
 		printf "\nEXTRA\n"
-		printf "Make opts          : $(($(nproc)+1))\n"
-		printf "PORTDIR            : ${port}\n"
-		printf "kver               : ${kver}\n"
-		printf "Tempdir            : ${tmpdir}\n"
+		printf "Make opts          : %s\n" "$(($(nproc)+1))"
+		printf "PORTDIR            : %s\n" "${port}"
+		printf "kver               : %s\n" "${kver}"
+		printf "Tempdir            : %s\n" "${tmpdir}"
 		printf "\n"
 		eselect kernel list
 	fi
@@ -210,7 +210,7 @@ fi
 
 if [ "${run_zfs_build}" = "1" ];then
 	zver_path="${zver}"
-	if [ "$(echo ${zver}|grep rc)" ];then
+	if [ "$(echo "${zver}"|grep rc)" ];then
 		zver="${zver%%_rc*}"
 	fi
 
@@ -232,7 +232,7 @@ if [ "${run_zfs_build}" = "1" ];then
 			ebuild "${port}/sys-fs/zfs-kmod/zfs-kmod-${zver_path}.ebuild" clean configure
 		cd "${tmpdir}/portage/sys-fs/zfs-kmod-${zver_path}/work/${kmod}-${zver}" || die
 		./copy-builtin "${kdir}" || die
-		cd ..
+		cd .. || die
 		tar -cf - "${kmod}-${zver}" -P | zstd -T0 >| "${archive}" || die "ERROR: did not compress zfs work dir"
 		mv "${archive}" "${kmod_src}"
 		chown -R "${user}:${group}" "${kmod_src}"
diff --git a/mk7z b/mk7z
--- a/mk7z
+++ b/mk7z
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-#3.2.0
-#2019-05-06
+#3.3.0
+#2019-05-17
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -52,7 +52,7 @@ compress(){
 			if [ "${extra}" = "1" ];then
 				printf "\n"
 				printf "${YEL}Profile\t: single${NC}\n"
-				printf "${YEL}File\t: ${f%%}${NC}\n"
+				printf "${YEL}File\t: %s${NC}\n" "${f%%}"
 			fi
 			nice -19 \
 				7z a -t7z -m0=lzma2 -md=1024m -mmf=bt4 -mmt=off -ms=off -myx=9 -mx=9 -mfb=276 \
@@ -63,7 +63,7 @@ compress(){
 			if [ "${extra}" = "1" ];then
 				printf "\n"
 				printf "${YEL}Profile\t: multi${NC}\n"
-				printf "${YEL}File\t: ${f%%}${NC}\n"
+				printf "${YEL}File\t: %s${NC}\n" "${f%%}"
 			fi
 			nice -19 \
 				7z a -t7z -m0=lzma2 -md=1024m -mmf=bt4 -mmt=on -mmtf=on -myx=9 -mx=9 -mfb=276 \
@@ -78,14 +78,14 @@ compress(){
 			;;
 		test)
 			if [ "${f##*.}" = "7z" ] || [ "${f##*.}" = "zip" ];then
-				printf "${YEL}TEST${NC}\t$(echo ${f%%}|cut -c 1-80)\n"
+				printf "${YEL}TEST${NC}\t%s\n" "$(echo "${f%%}"|cut -c 1-80)"
 				printf "\033[A"
 				if [ -n "$(nice -19 7z t "${f%%}"|grep Ok)" ];then
-					printf "${GRE}PASSED${NC}\t${f%%}\n"
+					printf "${GRE}PASSED${NC}\t%s\n" "${f%%}"
 					P=$((P+1))
 				else
-					printf "${f}\n">>failed.txt
-					printf "${RED}FAILED${NC}\t${f%%}\n"
+					printf "%s\n" "${f}">>failed.txt
+					printf "${RED}FAILED${NC}\t%s\n" "${f%%}"
 					F=$((F+1))
 				fi
 			fi;;
@@ -93,7 +93,7 @@ compress(){
 
 	if [ "$?" -eq 0 ] && ! [ "${comp_type}" = "test" ] && [ "${orig_rm}" = "1" ] && [ -f "${f%%}.7z" ];then
 		if [ -n "$(${0} -t "${f%%}.7z"|grep FAILED)" ];then
-			printf "${RED}FAILED${NC} test for: ${f%%}.7z\n${YEL}Not removing original${NC}: "${f%%}"\n"
+			printf "${RED}FAILED${NC} test for: %s.7z\n${YEL}Not removing original${NC}: %s\n" "${f%%}" "${f%%}"
 		else
 			rm -r "${f%%}"
 		fi
@@ -103,19 +103,22 @@ compress(){
 P="0"
 F="0"
 extra="0"
+total="0"
 orig_rm="0"
 comp_dir="0"
 comp_file="0"
+
 
 test_post="1"
 file_list=""
 comp_type="multi"
 test_post_fancy="1"
-. $(dirname "$0")/colors.sh
 
 delim=",ßßß,"
 
-while getopts "SMTROetpdfhxz" OPT;do
+. "$(dirname "$0")/colors.sh"
+
+while getopts "SMTROPetdfhxz" OPT;do
 	case "$OPT" in
 		S) comp_type="single";;
 		M) comp_type="multi";;
@@ -140,14 +143,14 @@ if [ -n "${1}" ];then
 		if [ -e "${f}" ];then
 			compress
 		else
-			printf "\n${RED}Input does not exist${NC}: ${1}\n\n"
+			printf "\n${RED}Input does not exist${NC}: %s\n\n" "${1}"
 		fi
 		if [ -n "${2}" ];then shift;else break;fi
 	done
-elif [ "${comp_dir}" = "1" ] || [ "${comp_files}" = "1" ];then
+elif [ "${comp_dir}" = "1" ] || [ "${comp_file}" = "1" ];then
 	for f in *; do
 		if [ "${comp_dir}" = "1" ] && [ -d "${f%%}" ];then compress;fi
-		if [ "${comp_files}" = "1" ] && [ -f "${f%%}" ];then compress;fi
+		if [ "${comp_file}" = "1" ] && [ -f "${f%%}" ];then compress;fi
 	done
 else
 	printf "\n${RED}No input files${NC}\n\n";exit
@@ -167,8 +170,8 @@ fi
 if [ "${comp_type}" = "test" ] && [ "${test_post_fancy}" = "1" ];then
 	T="$((P+F))"
 	if ! [ "${total}" = "0" ];then
-		printf "\n${YEL}TOTAL${NC} \t${T}\n"
-		if ! [ "${P}" = "0" ];then printf "${GRE}PASSED${NC}\t${P}\n";fi
-		if ! [ "${F}" = "0" ];then printf "${RED}FAILED${NC}\t${F}\n";fi
+		printf "\n${YEL}TOTAL${NC} \t%s\n" "${T}"
+		if ! [ "${P}" = "0" ];then printf "${GRE}PASSED${NC}\t%s\n" "${P}";fi
+		if ! [ "${F}" = "0" ];then printf "${RED}FAILED${NC}\t%s\n" "${F}";fi
 	fi
 fi
diff --git a/mkxz b/mkxz
--- a/mkxz
+++ b/mkxz
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-#6.1.0
-#2019-01-18
+#6.2.0
+#2019-05-17
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -21,12 +21,17 @@ die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }
 compress(){
 	if [ -d "${f%%}" ] && ! [ "${comp_type}" = "status" ];then comp_type="dir";fi
 	case "${comp_type}" in
-		status) tar --xattrs -${V}Scf - "${f%%}" -P | pv -s $(du -sb "${f%%}" | awk '{print $1}') | "$C" "$A" >| "${f%%}.tar.${E}" || die "Compression failed for: ${f%%}";;
-		dir) tar --xattrs -${V}Scf - "${f%%}" -P | "$C" "$A" >| "${f%%}.tar.${E}" || die "Compression failed for: ${f%%}";;
+		status)
+			tar --xattrs -${V}Scf - "${f%%}" -P | \
+				pv -s "$(du -sb "${f%%}" | awk '{print $1}')" | \
+				"$C" "$A" >| "${f%%}.tar.${E}" || die "Compression failed for: ${f%%}";;
+		dir)
+			tar --xattrs -${V}Scf - "${f%%}" -P | \
+				"$C" "$A" >| "${f%%}.tar.${E}" || die "Compression failed for: ${f%%}";;
 		file) "$C" "$A" "${f%%}" || die "Compression failed for: ${f%%}";;
 	esac
 
-	if [ "${comp_rm}" = "1" ];then rm -r "${f%%}";fi
+	if [ "${orig_rm}" = "1" ];then rm -r "${f%%}";fi
 }
 
 orig_rm="0"
@@ -88,7 +93,7 @@ if [ -n "${1}" ];then
 		if [ -e "${f}" ];then
 			compress
 		else
-			printf "\nInput is none existent : ${1}\n\n"
+			printf "\nInput is none existent : %s\n\n" "${1}"
 		fi
 		if [ -n "${2}" ];then shift;else break;fi
 	done
diff --git a/tape-utils b/tape-utils
--- a/tape-utils
+++ b/tape-utils
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-#1.2.0
-#2019-01-17
+#1.3.0
+#2019-05-17
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -20,7 +20,8 @@
 die(){ /bin/echo -e "$*";exit 1; }
 if [ "$(id -u)" -ne 0 ];then die "Requires root, exiting";fi
 
-. $(dirname "$0")/colors.sh
+. "$(dirname "$0")/colors.sh"
+
 tape="/dev/st0"
 
 t_rewind(){ mt -f "$tape" rewind; }
@@ -34,10 +35,10 @@ t_list(){ tar -tf "${tape}"; }
 t_cdloc(){
 	#dont tar unneeded paths
 	if [ -d "${target}" ];then
-		cd "${target}/.."
+		cd "${target}/.." || die
 	elif [ -f "${target}" ];then
-		target="$(dirname ${target})"
-		cd "${target}"
+		target="$(dirname "${target}")"
+		cd "${target}" || die
 	else
 		printf "not a file or directory\n"
 	fi
@@ -45,7 +46,7 @@ t_cdloc(){
 
 t_confirm_erase(){
 	printf "Erase current tape: y/n\n"
-	read confirm
+	read -r confirm
 	if echo "${confirm}" | grep -iq "^y" ;then
 		t_erase
 	else
@@ -81,40 +82,13 @@ t_verify(){
 	tar -tvf "${tape}"
 }
 
-hlp(){
-	printf " Tape drive is : %s\n" "$tape"
-	printf " -b\tbackup \$1 at end of last backup on $tape\n"
-	printf " -B\tbackup \$1 at start, overwriting existing, on $tape\n"
-	printf " -e\teject tape\n"
-	printf " -g\trestore from begining of $tape to \$1\n"
-	printf " -h\tPrint this help\n"
-	printf " -l\tlist contents of $tape\n"
-	printf " -L\tprint web links\n"
-	printf " -r\trewind tape\n"
-	printf " -R\ttape retensioning <only for tape read errors>\n"
-	printf " -s\tdrive status\n"
-	printf " -v\tverify files on current tape\n"
-	printf " -z\terase/rewind tape\n"
-	printf " -Z\terase/rewind/eject tape\n"
-}
-
-links(){
-	printf "https://www.cyberciti.biz/hardware/unix-linux-basic-tape-management-commands\n"
-	printf "https://www.cyberciti.biz/faq/unix-verify-tape-backup\n"
-	printf "https://www.cyberciti.biz/faq/linux-tape-backup-with-mt-and-tar-command-howto\n"
-	printf "https://community.hpe.com/t5/StoreEver-Tape-Storage/determining-free-space-on-tape-under-Linux/td-p/3624568\n"
-	printf "\n"
-}
-
-if [ -z "${1}" ];then hlp;exit;fi
+if [ -z "${1}" ];then "${0}" -h;exit;fi
 while getopts "B:b:eg:hHlRrsvZz" OPT;do
 	case "$OPT" in
 		b) target="$OPTARG";t_backup;;
 		B) target="$OPTARG";t_backup_overwrite;;
 		e) t_eject;;
 		g) target="$OPTARG";t_restore;;
-		h) hlp;exit;;
-		H) links;;
 		l) t_list;;
 		R) t_reten;;
 		r) t_rewind;;
@@ -122,6 +96,28 @@ while getopts "B:b:eg:hHlRrsvZz" OPT;do
 		v) t_verify;;
 		z) t_confirm_erase;t_rewind;;
 		Z) t_confirm_erase;t_rewind;t_eject;;
+		h)
+			printf " Tape drive is : %s\n" "${tape}"
+			printf " -b\tbackup \$1 at end of last backup on %s\n" "${tape}"
+			printf " -B\tbackup \$1 at start, overwriting existing, on %s\n" "${tape}"
+			printf " -e\teject tape\n"
+			printf " -g\trestore from begining of %s to \$1\n" "${tape}"
+			printf " -h\tPrint this help\n"
+			printf " -l\tlist contents of %s\n" "${tape}"
+			printf " -L\tprint web links\n"
+			printf " -r\trewind tape\n"
+			printf " -R\ttape retensioning <only for tape read errors>\n"
+			printf " -s\tdrive status\n"
+			printf " -v\tverify files on current tape\n"
+			printf " -z\terase/rewind tape\n"
+			printf " -Z\terase/rewind/eject tape\n"
+			exit;;
+		H)
+			printf "https://www.cyberciti.biz/hardware/unix-linux-basic-tape-management-commands\n"
+			printf "https://www.cyberciti.biz/faq/unix-verify-tape-backup\n"
+			printf "https://www.cyberciti.biz/faq/linux-tape-backup-with-mt-and-tar-command-howto\n"
+			printf "https://community.hpe.com/t5/StoreEver-Tape-Storage/determining-free-space-on-tape-under-Linux/td-p/3624568\n"
+			exit;;
 	esac
 done
 shift $((OPTIND - 1))
