fixes

diff --git a/gentoo-chroot b/gentoo-chroot
--- a/gentoo-chroot
+++ b/gentoo-chroot
@@ -1,6 +1,6 @@
 #!/bin/sh
-#5.4.0
-#2018-10-13
+#5.5.0
+#2018-10-17
 
 #Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
 #
@@ -28,28 +28,39 @@ mount_sys(){
 	mount --rbind /dev "${ch}/dev"
 }
 
+mount_in_chroot(){
+	chroot "${ch}" mount /tmp
+	chroot "${ch}" mount /run
+	chroot "${ch}" mount /usr/src
+	chroot "${ch}" mount /var/cache
+}
+
 mount_bind(){
 	portage=$(grep PORTDIR= /etc/portage/make.conf|sed 's/PORTDIR=//g;s/"//g')
 	portagelocal=$(grep PORTDIR_OVERLAY= /etc/portage/make.conf|sed 's/PORTDIR_OVERLAY=//g;s/"//g')
-	#packages=$(grep PKDIR= /etc/portage/make.conf|sed 's/PKDIR=//g;s/"//g')
-	#distfiles=$(grep DISTDIR= /etc/portage/make.conf|sed 's/DISTDIR=//g;s/"//g')
+	layman="/var/db/repos/layman"
+	pkg=$(grep PKGDIR= /etc/portage/make.conf|sed 's/PKGDIR=//g;s/"//g')
+	dist=$(grep DISTDIR= /etc/portage/make.conf|sed 's/DISTDIR=//g;s/"//g')
+
 	if ! [ -d "${ch}/${portage}" ];then mkdir -p "${ch}/${portage}";fi
 	if ! [ -d "${ch}/${portagelocal}" ];then mkdir -p "${ch}/${portagelocal}";fi
-	#if ! [ -d "${ch}/${distfiles}" ];then mkdir -p "${ch}/${distfiles}";fi
+	if ! [ -d "${ch}/${layman}" ];then mkdir -p "${ch}/${layman}";fi
+	if ! [ -d "${ch}/${pkg}" ];then mkdir -p "${ch}/${pkg}";fi
+	if ! [ -d "${ch}/${dist}" ];then mkdir -p "${ch}/${dist}";fi
+
+	mount --bind "${dist}" "${ch}/${dist}"
+	mount --bind "${pkg}" "${ch}/${pkg}"
+	mount --bind "${layman}" "${ch}/${layman}"
 	mount --bind "${portage}" "${ch}/${portage}"
 	mount --bind "${portagelocal}" "${ch}/${portagelocal}"
-	#mount --bind "${packages}" "${ch}/${packages}"
-	#mount --bind "${distfiles}" "${ch}/${distfiles}"
-	#TODO find better way
-	#mount --bind /var/db/repos/layman /mnt/gentoo/usr/layman
 }
 
 shell_check(){
-	if [ -f "${ch}"/bin/zsh ];then S="zsh"
-	elif [ -f "${ch}"/bin/bash ];then S="bash"
-	elif [ -f "${ch}"/bin/sh ];then S="sh"
+	if [ -f "${ch}/bin/zsh" ];then S="zsh"
+	elif [ -f "${ch}/bin/bash" ];then S="bash"
+	elif [ -f "${ch}/bin/sh" ];then S="sh"
 	else
-		printf "no shells in chroot location, ensure validity, exiting."
+		printf "no shells in chroot"
 		exit 1
 	fi
 }
@@ -88,10 +99,11 @@ esac
 case "${setup}" in
 	init)
 		shell_check
-		if ! [ -d "${ch}/proc" ];then printf "Invalid location. Missing ${ch}/proc\n";exit 1;fi
-		if ! [ -d "${ch}/sys" ];then printf "Invalid location. Missing ${ch}/sys\n";exit 1;fi
-		if ! [ -d "${ch}/dev" ];then printf "Invalid location. Missing ${ch}/dev\n";exit 1;fi
+		if ! [ -d "${ch}/proc" ];then printf "Missing ${ch}/proc\n";exit 1;fi
+		if ! [ -d "${ch}/sys" ];then printf "Missing ${ch}/sys\n";exit 1;fi
+		if ! [ -d "${ch}/dev" ];then printf "Missing ${ch}/dev\n";exit 1;fi
 		mount_sys
+		mount_in_chroot
 		if [ "${mountbind}" = "1" ];then mount_bind;fi
 		chroot "${ch}" /bin/${S}
 		;;
