support for zfs rc ebuilds

diff --git a/kernel-build b/kernel-build
--- a/kernel-build
+++ b/kernel-build
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-#2.14.2
-#2019-01-13
+#2.15.0
+#2019-05-10
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -173,7 +173,7 @@ case "${use_zfs_version}" in
 		zver=$(echo ${Z%%.ebuild}|awk '{print $NF}' FS=-) #clean up filename
 		unset Z
 		kmod="zfs" #build path
-		if [ "${use_distdir}" = "0" ];then export DISTDIR="${storage}/distfiles";fi #keep sources on dist-clean
+		if [ "${use_distdir}" = "0" ];then export DISTDIR="${storage}/distfiles";fi #keep sources on eclean-dist
 		;;
 esac
 
@@ -209,6 +209,13 @@ if [ "${run_intro}" = "1" ];then
 fi
 
 if [ "${run_zfs_build}" = "1" ];then
+	zver_path="${zver}"
+	if [ "$(echo ${zver}|grep rc)" ];then
+		zver="${zver%%_rc*}"
+	fi
+
+	archive="zfs-${zver}.tar.zst"
+
 	if [ "${run_kmod_build}" = "1" ];then
 		cdkdir
 		msc
@@ -222,12 +229,12 @@ if [ "${run_zfs_build}" = "1" ];then
 		if [ -d "${kmod_src}" ];then rm --preserve-root -r "${kmod_src}";fi
 		mkdir -p "${kmod_src}"
 		CC=gcc env EXTRA_ECONF="--with-linux=${kdir} --enable-linux-builtin" \
-			ebuild "${port}/sys-fs/zfs-kmod/zfs-kmod-${zver}.ebuild" clean configure
-		cd "${tmpdir}/portage/sys-fs/zfs-kmod-${zver}/work/${kmod}-${zver}" || die
+			ebuild "${port}/sys-fs/zfs-kmod/zfs-kmod-${zver_path}.ebuild" clean configure
+		cd "${tmpdir}/portage/sys-fs/zfs-kmod-${zver_path}/work/${kmod}-${zver}" || die
 		./copy-builtin "${kdir}" || die
 		cd ..
-		tar -cf - "${kmod}-${zver}" -P | zstd -T0 >| "zfs-${zver}.tar.zst" || die "ERROR: did not compress zfs work dir"
-		mv "zfs-${zver}.tar.zst" "${kmod_src}"
+		tar -cf - "${kmod}-${zver}" -P | zstd -T0 >| "${archive}" || die "ERROR: did not compress zfs work dir"
+		mv "${archive}" "${kmod_src}"
 		chown -R "${user}:${group}" "${kmod_src}"
 
 		if [ "${use_modules}" = "0" ];then
@@ -236,7 +243,7 @@ if [ "${run_zfs_build}" = "1" ];then
 		fi
 	else
 		cd "${kmod_src}" || die
-		tar -I zstd -xf "zfs-${zver}.tar.zst" -C "${tmpdir}" || die "ERROR: cannot extract zfs work dir"
+		tar -I zstd -xf "${archive}" -C "${tmpdir}" || die "ERROR: cannot extract zfs work dir"
 		cd "${tmpdir}/${kmod}-${zver}" || die
 		./copy-builtin "${kdir}" || die "ERROR: copy-builtin failed"
 	fi
