general improvements

diff --git a/kernel-build b/kernel-build
--- a/kernel-build
+++ b/kernel-build
@@ -1,6 +1,6 @@
 #!/bin/sh
-#2.10.0
-#2018-12-08
+#2.11.0
+#2018-12-13
 
 #Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
 #
@@ -21,8 +21,6 @@
 
 #hard requirments
 #>=linux-4.17.0 : >=zfs-0.8.0 / git | 1.x.x for previous support
-	#removal of spl
-	#kernel : silentoldconfig > syncconfig
 
 #storage dirs - need to exist
 #/home/${user}/.config/kernel/{config,distfiles,src}
@@ -33,12 +31,14 @@
 #PORTDIR PORTDIR_OVERLAY are set in make.conf, PORTAGE_OVERLAY is also only one repo
 #$run_kernel_bump is based om my own config and others CONFIG_* options may be needed based on kenrel config
 
-#What this script does, basically
+###What this script does, basically###
+
 ###if no preconfigured kmod_zfs sources exist###
 #runs configure phase on kmod-zfs ebuild
-#saves work to tar.xz file in $kmod_src
+#saves work/ to tar.xz file in $kmod_src
 #installs configured kmod-zfs to /usr/src/linux
 #builds kernel
+
 ###if preconfigured kmod_zfs sources exist###
 #moves saved work in tar.xz file to /usr/src/linux
 #builds kernel
@@ -46,22 +46,24 @@
 die(){ echo >&2 "$@";exit 1; }
 if [ "$(id -u)" -ne 0 ];then die "Requires root";fi
 
-finish(){ if [ -d "${tmpdir}" ];then rm --preserve-root -r "${tmpdir}";fi }
+finish(){ if [ -d "${tmpdir}" ];then rm --preserve-root -r "${tmpdir}";fi; }
 trap 'exit 1' INT HUP QUIT TERM USR1
 trap finish EXIT
 tmpdir=$(mktemp -d)
 chmod 755 "${tmpdir}"
 
 msc(){ make syncconfig; }
+cdkdir(){ cd "${kdir}" || die "ERROR: can not cd into kenrel directory"; }
 
 user="brandon"
 group="${user}"
 storage="/home/${user}/.config/kernel"
 kdir="/usr/src/linux"
 use_zfs_version="git"
-extra="0"
+intro_extra="0"
 
 run_intro="1"
+run_emerge="1"
 run_zfs_build="1"
 run_kmod_build="0"
 run_kernel_post="1"
@@ -69,13 +71,24 @@ run_kernel_build="1"
 run_kernel_install="1"
 use_local_zfs_ebuild="0"
 
-if ! [ -e "${kdir}" ];then die "${kdir} is not a valid symlink to kernel sources";fi
+if ! [ -e "${kdir}" ];then die "ERROR: ${kdir} is not a valid symlink";fi
 if ! [ -d "${storage}/config" ];then mkdir -p "${storage}/config";fi
-if [ -z "$(grep CONFIG_MODULES=y ${kdir}/.config)" ];then use_modules="0";else use_modules="1";fi
+
+if ! [ -f "${kdir}/.config" ];then
+	if [ -f "/proc/config.gz" ];then
+		printf "WARNING: no kernel config found, using config from running kernel\n"
+		zcat /proc/config.gz >| /usr/src/linux/.config || die
+		cdkdir
+		msc
+	else
+		die "ERROR: no config in kenrel directory and no running config is available"
+	fi
+fi
+
+if [ -n "$(grep CONFIG_MODULES=y ${kdir}/.config)" ];then use_modules="1";else use_modules="0";fi
 
 ksym=$(readlink -f ${kdir}|awk '{print $NF}' FS=/)
-is_rc=$(echo ${ksym}|grep rc) #would match /usr/src/
-if [ -z ${is_rc} ];then
+if [ -z $(echo ${ksym}|grep rc) ];then #would match /usr/src/
 	kver=$(echo ${ksym}|awk 'BEGIN{FS=OFS="."} NF--')
 else
 	kver=$(echo ${ksym}|sed s'/.$//')
@@ -90,42 +103,37 @@ while true;do
 		-g) use_zfs_version="git";shift;;
 		-r) use_zfs_version="release";shift;;
 		-c) run_kmod_build="1";shift;;
+		-e) run_emerge="0";shift;;
 		-I) run_intro="0";shift;;
 		-i) run_kernel_install="0";run_kernel_post="0";shift;;
 		-m) use_modules="1";shift;;
 		-p) run_kernel_post="0";shift;;
 		-l) use_local_zfs_ebuild="1";shift;;
 		-x) run_zfs_build="0";shift;;
-		-z) run_zfs_build="1";use_modules="0";run_kernel_build="0";run_kernel_post="0";shift;;
-		-v) extra="1";shift;;
+		-z) run_zfs_build="1";run_kernel_build="0";run_kernel_post="0";shift;;
+		-v) intro_extra="1";shift;;
 		-h)
 			printf "GENERAL\n"
 			printf " -B\tforce run_kernel_bump=1\n"
 			printf " -h\tprint this help\n"
-			printf " -I\tdo not run kernel_intro()\n"
-			printf " -v\textra vars in kenrel_intro()\n"
+			printf " -I\tdisable  intro\n"
+			printf " -v\textra vars in intro\n"
 			printf "\nZFS\n"
-			printf " -c\tconfigure kmod even if preconfigured sources exist\n"
-			printf " -g\tuse zfs git\n"
-			printf " -r\tuse zfs release\n"
-			printf " -l\tforce use PORTDIR_OVERLAY repo\n"
+			printf " -c\tbuild kmod even if preconfigured sources exist\n"
+			printf " -e\tdisable running emerge in post\n"
+			printf " -g\tuse git ebuild\n"
+			printf " -r\tuse release ebuild\n"
+			printf " -l\tuse local repo in PORTDIR_OVERLAY\n"
 			printf "\nKERNEL BUILDING\n"
-			printf " -i\tdo not install kenrel and do not run kernel_post()\n"
+			printf " -i\tbuild kernel but do not install or run post\n"
 			printf " -m\tenable module build\n"
-			printf " -p\tdo not run kernel_post()\n"
-			printf " -x\tdo not run kernel_zfs_build()\n"
-			printf " -z\tonly run kernel_zfs_build()\n"
+			printf " -p\tdisable post actions\n"
+			printf " -x\tdisable zfs build, all checks must still pass, script becomes fancy 'make;make install'\n"
+			printf " -z\tonly run zfs build, will install zfs into kenrel tree\n"
 			exit;;
 		*) break;;
 	esac
 done
-
-if [ -f "/proc/config.gz" ] && ! [ -f "${kdir}/.config" ];then
-	printf "WARNING: No kernel config found, using running kernel config.\n"
-	zcat /proc/config.gz >| /usr/src/linux/.config || die
-	cd "${kdir}" || die
-	msc
-fi
 
 #CONFIG_MODULES and CONFIG_KALLSYMS are required to build kmod
 #which are not needed at runtime if zfs is build into the kernel.
@@ -144,7 +152,7 @@ while [ "${run_kernel_bump}" = "1" ];do
 		printf "Enter to config switch config : "
 		read z;unset z
 		if [ -f "${switch_kconf}" ];then rm "${switch_kconf}";fi
-		cd "${kdir}" || die
+		cdkdir
 		cp .config "${tmpdir}"
 		make nconfig
 		mv .config "${switch_kconf}"
@@ -158,7 +166,8 @@ if [ "${use_local_zfs_ebuild}" = "0" ];then
 	port=$(grep PORTDIR= /etc/portage/make.conf|sed 's/PORTDIR=//g;s/"//g')
 else
 	port=$(grep PORTDIR_OVERLAY= /etc/portage/make.conf|sed 's/PORTDIR_OVERLAY=//g;s/"//g')
-	if ! [ -d "${port}/sys-fs/zfs-kmod" ];then die "No local ebuild found";fi
+	if ! [ -d "${port}/sys-fs/zfs" ];then die "ERROR: missing directory ${port}/sys-fs/zfs";fi
+	if ! [ -d "${port}/sys-fs/zfs-kmod" ];then die "ERROR: missing directory ${port}/sys-fs/zfs-kmod";fi
 fi
 
 case "${use_zfs_version}" in
@@ -168,14 +177,18 @@ case "${use_zfs_version}" in
 		;;
 	release)
 		Z=$(ls -1A --ignore=*9999* ${port}/sys-fs/zfs|sort -V|tail -n1)
-		zver=$(echo ${Z%???????}|awk '{print $NF}' FS=-) #clean up filename
+		zver=$(echo ${Z%%.ebuild}|awk '{print $NF}' FS=-) #clean up filename
 		unset Z
 		kmod="zfs" #build path
 		export DISTDIR="${storage}/distfiles" #keep sources on dist-clean, but have to manually remove old
 		;;
 esac
+
+if ! [ -f "${port}/sys-fs/zfs/zfs-${zver}.ebuild" ];then die "ERROR: missing zfs-${zver}.ebuild";fi
+if ! [ -f "${port}/sys-fs/zfs-kmod/zfs-kmod-${zver}.ebuild" ];then die "ERROR: missing zfs-kmod-${zver}.ebuild";fi
+
 kmod_src="${storage}/src/${kver}/${zver}"
-if ! [ -d "${kmod_src}" ];then run_kmod_build="1";fi #dont need to build if configured src exists
+if ! [ -d "${kmod_src}" ];then run_kmod_build="1";fi #need to build if configured src do not exists
 
 if [ "${run_intro}" = "1" ];then
 	printf "\n"
@@ -185,7 +198,7 @@ if [ "${run_intro}" = "1" ];then
 	printf "ZFS local ebuild   : ${use_local_zfs_ebuild}\n"
 	printf "Configure kmod     : ${run_kmod_build}\n"
 	printf "Enable modules     : ${use_modules}\n"
-	if [ "${extra}" = "1" ];then
+	if [ "${intro_extra}" = "1" ];then
 		printf "\nEXTRA\n"
 		printf "Make opts          : $(($(nproc)+1))\n"
 		printf "PORTDIR            : ${port}\n"
@@ -201,16 +214,14 @@ fi
 
 if [ "${run_zfs_build}" = "1" ];then
 	if [ "${run_kmod_build}" = "1" ];then
-		cd "${kdir}" || die
+		cdkdir
 		msc
 		if [ "${use_modules}" = "0" ];then
 			mv .config "${tmpdir}"
 			cp "${switch_kconf}" .config
 		fi
 		make prepare
-	fi
 
-	if [ "${run_kmod_build}" = "1" ];then
 		export PORTAGE_TMPDIR="${tmpdir}"
 		if [ -d "${kmod_src}" ];then rm --preserve-root -r "${kmod_src}";fi
 		mkdir -p "${kmod_src}"
@@ -219,41 +230,44 @@ if [ "${run_zfs_build}" = "1" ];then
 		cd "${tmpdir}/portage/sys-fs/zfs-kmod-${zver}/work/${kmod}-${zver}" || die
 		./copy-builtin "${kdir}" || die
 		cd ..
-		tar --xattrs -cvf - "${kmod}-${zver}" -P | XZ_OPT="-e9" xz >| "zfs-${zver}.tar.xz"
+		tar --xattrs -cvf - "${kmod}-${zver}" -P | XZ_OPT="-e9" xz >| "zfs-${zver}.tar.xz" #smaller archive, do not question it
 		mv "zfs-${zver}.tar.xz" "${kmod_src}"
 		chown -R "${user}:${group}" "${kmod_src}"
+
+		if [ "${use_modules}" = "0" ];then
+			rm "${kdir}/.config"
+			mv "${tmpdir}/.config" "${kdir}"
+		fi
 	else
 		cd "${kmod_src}" || die
 		tar --xattrs -xJf "zfs-${zver}.tar.xz" -C "${tmpdir}"
 		cd "${tmpdir}/${kmod}-${zver}" || die
-		./copy-builtin "${kdir}" || die
+		./copy-builtin "${kdir}" || die "ERROR: copy-builtin failed"
 	fi
 
-	if [ "${run_kmod_build}" = "1" ] && [ "${use_modules}" = "0" ];then
-		rm "${kdir}/.config"
-		mv "${tmpdir}/.config" "${kdir}"
-	fi
 fi
 
 if [ "${run_kernel_build}" = "1" ];then
-	cd "${kdir}" || die
+	cdkdir
 	msc
-	nice -19 make -j$(($(nproc)+1)) || die
-	if [ "${use_modules}" = "1" ];then make modules_install;fi
-	if [ "${run_kernel_install}" = "1" ];then make install;fi
+	nice -19 make -j$(($(nproc)+1)) || die "ERROR: kernel build failed"
+	if [ "${run_kernel_install}" = "1" ];then
+		if [ "${use_modules}" = "1" ];then make modules_install;fi
+		make install
+	fi
 fi
 
 if [ "${run_kernel_post}" = "1" ];then
-	if [ "${run_zfs_build}" = "1" ];then
+	if [ "${run_emerge}" = "1" ];then
 		if [ "${run_kmod_build}" = "1" ] && [ "${use_zfs_version}" = "git" ];then
 			#always rebuild zfs when building git
 			emerge --ignore-default-opts --oneshot --quiet sys-fs/zfs
-		else
-			#only runs on non-git and on version bump
+		elif [ "${run_kmod_build}" = "1" ] && [ "${use_zfs_version}" = "release" ];then
+			#only builds on non-git and on version bump
 			emerge --ignore-default-opts --oneshot --quiet --update sys-fs/zfs
 		fi
+		if [ "${use_modules}" = "1" ];then emerge --ignore-default-opts --oneshot --jobs @module-rebuild;fi
 	fi
-	if [ "${use_modules}" = "1" ];then emerge --ignore-default-opts --oneshot --jobs --quiet @module-rebuild;fi
 	kernel-initramfs-genkernel
 	kernel-grub
 	kernel-clean-src -c
