fix tar

diff --git a/kernel-build b/kernel-build
--- a/kernel-build
+++ b/kernel-build
@@ -1,6 +1,6 @@
 #!/bin/sh
-#2.14.0
-#2018-01-11
+#2.14.1
+#2018-01-12
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -236,7 +236,7 @@ if [ "${run_zfs_build}" = "1" ];then
 		fi
 	else
 		cd "${kmod_src}" || die
-		tar -xf -I zstd "zfs-${zver}.tar.zst" -C "${tmpdir}" || die "ERROR: cannot extract zfs work dir"
+		tar -I zstd -xf "zfs-${zver}.tar.zst" -C "${tmpdir}" || die "ERROR: cannot extract zfs work dir"
 		cd "${tmpdir}/${kmod}-${zver}" || die
 		./copy-builtin "${kdir}" || die "ERROR: copy-builtin failed"
 	fi
