conf file to specify zfs version to use flag to not clean kernel src dir

diff --git a/kernel-build b/kernel-build
--- a/kernel-build
+++ b/kernel-build
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
-#2.16.0
-#2019-05-17
+#2.18.0
+#2019-05-24
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -58,7 +58,6 @@ group="${user}"
 storage="/home/${user}/.config/kernel"
 ksym="/usr/src/linux"
 kdir="$(readlink -f ${ksym})"
-use_zfs_version="git"
 
 run_intro="1"
 run_emerge="1"
@@ -67,10 +66,22 @@ run_kernel_post="1"
 run_kernel_build="1"
 run_kernel_install="1"
 
+clean_kernel_src="1"
+
 intro_extra="0"
 use_distdir="0"
 run_kmod_build="0"
 use_local_zfs_ebuild="0"
+
+. "$(dirname "$0")/utils.sh"
+if [ -f "${extra}/kernel-build" ];then
+	#file must be one line with either 'git' or 'release'
+	#this will be changed
+	use_zfs_version="$(cat "${extra}/kernel-build")"
+else
+	#printf "No config file\n"
+	use_zfs_version="git"
+fi
 
 if ! [ -e "${ksym}" ];then die "ERROR: ${ksym} is not a valid symlink";fi
 if ! [ -d "${storage}/config" ];then mkdir -p "${storage}/config";fi
@@ -96,7 +107,7 @@ esac
 switch_kconf="${storage}/config/${kver}-config"
 if [ -f "${switch_kconf}" ];then run_kernel_bump="0";else run_kernel_bump="1";fi
 
-while getopts "BbdgrceIimplxzvh" OPT;do
+while getopts "BCEbdgrceIimplxzvh" OPT;do
 	case "$OPT" in
 		B) run_kernel_bump="1";;
 		b) run_kernel_bump="0";;
@@ -113,12 +124,15 @@ while getopts "BbdgrceIimplxzvh" OPT;do
 		x) run_zfs_build="0";;
 		v) intro_extra="1";;
 		z) run_zfs_build="1";run_kernel_build="0";run_kernel_post="0";;
+		C) clean_kernel_src="0";;
+		E) $EDITOR "${extra}/kernel-build";;
 		h)
 			printf "GENERAL\n"
 			printf " -b\tforce run_kernel_bump=0\n"
 			printf " -B\tforce run_kernel_bump=1\n"
+			printf " -E\tEdit config file\n"
 			printf " -h\tprint this help\n"
-			printf " -I\tdisable  intro\n"
+			printf " -I\tdisable intro\n"
 			printf " -v\textra vars in intro\n"
 			printf "\nZFS\n"
 			printf " -c\tbuild kmod even if preconfigured sources exist\n"
@@ -128,6 +142,7 @@ while getopts "BbdgrceIimplxzvh" OPT;do
 			printf " -r\tuse release ebuild\n"
 			printf " -l\tuse local repo in PORTDIR_OVERLAY\n"
 			printf "\nKERNEL BUILDING\n"
+			printf " -C\tdisable cleaning kenrel kernel source dir\n"
 			printf " -i\tbuild kernel but do not install or run post\n"
 			printf " -m\tenable module build\n"
 			printf " -p\tdisable post actions\n"
@@ -231,7 +246,7 @@ if [ "${run_zfs_build}" = "1" ];then
 		CC=gcc env EXTRA_ECONF="--with-linux=${kdir} --enable-linux-builtin" \
 			ebuild "${port}/sys-fs/zfs-kmod/zfs-kmod-${zver_path}.ebuild" clean configure
 		cd "${tmpdir}/portage/sys-fs/zfs-kmod-${zver_path}/work/${kmod}-${zver}" || die
-		./copy-builtin "${kdir}" || die
+		./copy-builtin "${kdir}" || die "ERROR: copy-builtin failed"
 		cd .. || die
 		tar -cf - "${kmod}-${zver}" -P | zstd -T0 >| "${archive}" || die "ERROR: did not compress zfs work dir"
 		mv "${archive}" "${kmod_src}"
@@ -272,5 +287,5 @@ if [ "${run_kernel_post}" = "1" ];then
 	fi
 	kernel-initramfs-genkernel
 	kernel-grub
-	kernel-clean-src -c
+	if [ "${clean_kernel_src}" = "1" ];then kernel-clean-src -c;fi
 fi
