refactoring

diff --git a/mk7z b/mk7z
--- a/mk7z
+++ b/mk7z
@@ -1,8 +1,8 @@
 #!/bin/sh
-#2.14.0
-#2018-12-30
+#3.0.0
+#2018-01-17
 
-#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
+#Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
 #This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -17,70 +17,86 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-#resources
-#https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm
-
 #notes
-#m0=lzma2 is fast mode but produces samller archives
+#resources: https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm
+#m0=lzma2 is fast mode but produces samller archives, needs more testing
 #-m prefixes all options or -m0=lzma:a1:d25 for sub options
 
-#TODO
-#code cleanup
-#imporve testing
-
-comp_file="0"
-comp_dir="0"
-orig_rm="0"
-test_only="0"
-test_post="1"
-
-profile="multi"
-
+die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }
+test_file_list(){ if [ -f "${f%%}.7z" ];then file_list="${file_list} ${f%%}.7z";fi; }
 compress(){
-	case "${profile}" in
+	case "${comp_type}" in
 		single)
 			printf "\n***NOTICE*** The compression profile being used will probably use over 10G of ram\n"
 			printf "Profile : single\n"
-			nice -19 7z a -t7z -m0=lzma2 -md=1024m -mmf=bt4 -mmt=off -ms=off -myx=9 -mx=9 -mfb=276 -ms=on -mhc=on -mtm=off -mtc=off -mta=off "${f%%}.7z" "${f%%}"
+			printf "File    : ${f%%}\n"
+			nice -19 \
+				7z a -t7z -m0=lzma2 -md=1024m -mmf=bt4 -mmt=off -ms=off -myx=9 -mx=9 -mfb=276 \
+				-ms=on -mhc=on -mtm=off -mtc=off -mta=off "${f%%}.7z" "${f%%}" || die "Compression failed for: ${f%%}"
+			test_file_list
 			;;
 		multi)
 			printf "\n***NOTICE*** The compression profile being used will probably use =LOTS= of ram\n"
 			printf "Profile : multi\n"
-			nice -19 7z a -t7z -m0=lzma2 -md=1024m -mmf=bt4 -mmt=on -mmtf=on -myx=9 -mx=9 -mfb=276 -mhc=on -ms=on -mtm=off -mtc=off -mta=off "${f%%}.7z" "${f%%}"
+			printf "File    : ${f%%}\n"
+			nice -19 \
+				7z a -t7z -m0=lzma2 -md=1024m -mmf=bt4 -mmt=on -mmtf=on -myx=9 -mx=9 -mfb=276 \
+				-mhc=on -ms=on -mtm=off -mtc=off -mta=off "${f%%}.7z" "${f%%}" || die "Compression failed for: ${f%%}"
+			test_file_list
 			;;
-		test) nice -19 7z a -t7z -m0=lzma2 -md=1024m -mmf=bt4 -mmt=off -myx=9 -mx=9 -mfb=276 -ms=on "${f%%}.7z" "${f%%}";;
+		old)
+			nice -19 \
+				7z a -t7z -m0=lzma2 -md=1024m -mmf=bt4 -mmt=off -myx=9 -mx=9 -mfb=276 -ms=on \
+				"${f%%}.7z" "${f%%}" || die "Compression failed for: ${f%%}"
+			test_file_list
+			;;
+		test)
+			if [ "${f##*.}" = "7z" ] || [ "${f##*.}" = "zip" ];then
+				if [ -n "$(nice -19 7z t "${f%%}"|grep Ok)" ];then
+					printf "${GRE}PASSED${NC}\t${f%%}\n"
+					P=$((P+1))
+				else
+					printf "${f}\n">>failed.txt
+					printf "${RED}FAILLED${NC}\t${f%%}\n"
+					F=$((F+1))
+				fi
+			fi;;
 	esac
 
-	#exit if non 0 exit code
-	out="$?"
-	if [ "${out}" -eq 0 ] && [ "${orig_rm}" = "1" ] && [ -f "${f%%}.7z" ];then
+	if [ "$?" -eq 0 ] && ! [ "${comp_type}" = "test" ] && [ "${orig_rm}" = "1" ] && [ -f "${f%%}.7z" ];then
 		if [ -n "$(${0} -t "${f%%}.7z"|grep FAILED)" ];then
-			printf "Test FAILED for : ${f%%}.7z\nNot removing original : "${f%%}"\n";exit 1
+			printf "Test ${RED}FAILED${NC} for: ${f%%}.7z\nNot removing original: "${f%%}"\n"
 		else
 			rm -r "${f%%}"
 		fi
 	fi
 }
 
-file_test(){
-	if [ "${f##*.}" = "7z" ] || [ "${f##*.}" = "zip" ];then
-		tst=$(nice -19 7z t "${f%%}"|grep Ok)
-		if ! [ -z "${tst}" ];then stat="PASSED"; else stat="FAILED";fi
-		if [ "${stat}" = "FAILED" ];then printf "${f}\n">>failed.txt;fi
-		printf "Test ${stat} for : ${f%%}\n"
-	fi
-}
+RED="\033[0;31m"
+GRE="\033[0;32m"
+YEL="\033[0;33m"
+NC="\033[0m"
 
-while getopts "SMTtpdfsxzh" OPT;do
+orig_rm="0"
+comp_dir="0"
+comp_file="0"
+
+test_post="1"
+file_list=""
+comp_type="multi"
+test_post_fancy="1"
+
+while getopts "SMTROtpdfhxz" OPT;do
 	case "$OPT" in
-		S) profile="single";;
-		M) profile="multi";;
-		T) profile="test";;
-		t) test_only="1";test_post="0";comp_file="1";;
+		S) comp_type="single";;
+		M) comp_type="multi";;
+		O) comp_type="old";;
+		t) comp_type="test";test_post="0";P="0";F="0";printf "${YEL}RUNNING TESTS${NC}\n";;
+		T) comp_type="test";test_post="0";test_post_fancy="0";;
 		P) test_post="0";;
 		d) comp_dir="1";;
 		f) comp_file="1";;
-		s) orig_rm="1";;
+		R) orig_rm="1";test_post="0";;
 		x) comp_file="1";orig_rm="1";;
 		z) comp_dir="1";orig_rm="1";;
 		h)
@@ -88,14 +104,15 @@ while getopts "SMTtpdfsxzh" OPT;do
 			printf "\nPROFILES\n"
 			printf " -S\tSingle threaded, useful when hitting oom with multi\n"
 			printf " -M\tMultithreaded\n"
-			printf " -T\tTest\n"
+			printf " -O\tOld profile for testing\n"
 			printf "\nOTHER\n"
 			printf " -d\tcompress all directories\n"
 			printf " -f\tcompress all files\n"
 			printf " -h\tprint this help\n"
 			printf " -P\tDisable post compression test\n"
-			printf " -s\tcompress \$1, delete after compressed\n"
-			printf " -t\tTest all compress files or file passed in \$1\n"
+			printf " -R\tdelete after compressed, will test before deleting, disables post testing, works in all modes but test\n"
+			printf " -t\tTest file[s] passed in \$1\n"
+			printf " -T\tTest file[s] passed in \$1\n disable total output"
 			printf " -x\tcompress all files, delete original after compressed\n"
 			printf " -z\tcompress all directories, delete original after compressed\n"
 			exit;;
@@ -107,31 +124,33 @@ if [ -n "${1}" ];then
 	while true;do
 		f="${1%%}"
 		if [ -e "${f}" ];then
-			if [ "${test_only}" = "0" ];then compress;else file_test;fi
+			compress
 		else
-			printf "\n***\nInput is none existent : ${1}\n***\n"
+			printf "\nInput is none existent : ${1}\n\n"
 		fi
 		if [ -n "${2}" ];then shift;else break;fi
 	done
-elif [ "${comp_dir}" = "1" ] || [ "${comp_file}" = "1" ];then
+elif [ "${comp_dir}" = "1" ] || [ "${comp_files}" = "1" ];then
 	for f in *; do
-		if [ "${comp_dir}" = "1" ] && [ -d "${f}" ];then
-			if [ "${test_only}" = "0" ];then compress;else file_test;fi
-		fi
-		if [ "${comp_file}" = "1" ] && [ -f "${f}" ];then
-			if [ "${test_only}" = "0" ];then compress;else file_test;fi
-		fi
+		if [ "${comp_dir}" = "1" ] && [ -d "${f%%}" ];then compress;fi
+		if [ "${comp_files}" = "1" ] && [ -f "${f%%}" ];then compress;fi
 	done
 else
-	printf "Nothing to compress\n"
-	#printf "Something is broken\nDumping vars :\n"
-	#printf "\$1=$1\nprofile=${profile}\ncomp_file=${comp_file}\ncomp_dir=${comp_dir}\n"
-	#printf "orig_rm=${orig_rm}\ntest_only=${test_only}\ntest_post=${test_post}\n"
-	exit
+	printf "No input files\n";exit
 fi
 
-if [ "${test_post}" = "1" ];then
-	for f in *.7z; do
-		if [ -f "${f}" ];then file_test;fi
+if [ "${test_post}" = "1" ] && [ "${orig_rm}" = "0" ];then
+	for f in ${file_list}; do
+		if [ -f "${f}" ];then
+			comp_type="test"
+			compress
+		fi
 	done
+fi
+
+if [ "${comp_type}" = "test" ] && [ "${test_post_fancy}" = "1" ];then
+	T="$((P+F))"
+	if ! [ "${total}" = "0" ];then printf "\n${YEL}TOTAL${NC} \t${T}\n";fi
+	if ! [ "${P}" = "0" ];then printf "${GRE}PASSED${NC}\t${P}\n";fi
+	if ! [ "${F}" = "0" ];then printf "${RED}FAILED${NC}\t${F}\n";fi
 fi
diff --git a/mkxz b/mkxz
--- a/mkxz
+++ b/mkxz
@@ -1,6 +1,6 @@
 #!/bin/sh
-#5.4.2
-#2019-01-08
+#6.0.0
+#2019-01-17
 
 #Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
@@ -17,40 +17,40 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
+die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }
 compress(){
-	if [ -d "${f}" ];then
-		if [ ${comp_status} = "1" ];then
-			tar --xattrs --sparse -${V}cf - "${f%%}" -P | pv -s $(du -sb "${f%%}" | awk '{print $1}') | "$C" "$A" >| "${f%%}.tar.${E}"
-		else
-			tar --xattrs --sparse -${V}cf - "${f%%}" -P | "$C" "$A" >| "${f%%}.tar.${E}"
-		fi
-	elif [ -f "${f}" ];then
-		"$C" "$A" "${f%%}"
-	fi
+	case "${comp_type}" in
+		0) tar --xattrs -${V}Scf - "${f%%}" -P | pv -s $(du -sb "${f%%}" | awk '{print $1}') | "$C" "$A" >| "${f%%}.tar.${E}" || die "Compression failed for: ${f%%}";;
+		1) tar --xattrs -${V}Scf - "${f%%}" -P | "$C" "$A" >| "${f%%}.tar.${E}" || die "Compression failed for: ${f%%}";;
+		2) "$C" "$A" "${f%%}" || die "Compression failed for: ${f%%}";;
+	esac
+
 	if [ "${comp_rm}" = "1" ];then rm -r "${f%%}";fi
 }
 
-V=""
+orig_rm="0"
 comp_dir="0"
 comp_files="0"
-orig_rm="0"
-comp_status="0"
+
+V=""
+comp_type="2"
 mode="${0##*/mk}"
 
 while getopts "BGXSLZdfsxzvh" OPT;do
 	case "$OPT" in
+
+		d) comp_dir="1";comp_type="1";;
+		f) comp_files="1";;
+		s) orig_rm="1";;
+		S) comp_dir="1";comp_type="0";;
+		v) V="v";;
+		x) comp_dir="1";orig_rm="1";;
+		z) comp_files="1";orig_rm="1";comp_type="1";;
 		B) mode="bz2";;
 		G) mode="gz";;
 		L) mode="lz4";;
 		X) mode="xz";;
 		Z) mode="zst";;
-		d) comp_dir="1";;
-		f) comp_files="1";;
-		s) orig_rm="1";;
-		S) comp_status="1";;
-		x) comp_dir="1";orig_rm="1";;
-		z) comp_files="1";orig_rm="1";;
-		v) V="v";;
 		h)
 			printf " default will compress files passed in \$1\n"
 			printf " -d\tcompress all directories\n"
@@ -76,12 +76,11 @@ case "${mode}" in
 	bz2) C="bzip2";A="-k";E="bz2";;
 	lz4) C="lz4";A="-k";E="lz4";;
 	gz) C="gzip";A="-k";E="gz";;
-	xz) C="xz";A="-e9";E="xz";;
+	xz) C="xz";A="-e9";E="xz";XZ_OPT="-9e";;
 	zst) C="zstd";A="-T0";E="zst";;
 esac
 
-if [ -z "${C}" ] || [ -z "${E}" ];then printf "No compresion format set\n";exit 1;fi
-
+if [ -z "${C}" ];then printf "No compresion format set\n";exit 1;fi
 if [ -n "${1}" ];then
 	while true;do
 		f="${1%%}"
@@ -94,12 +93,8 @@ if [ -n "${1}" ];then
 	done
 elif [ "${comp_dir}" = "1" ] || [ "${comp_files}" = "1" ];then
 	for f in *; do
-		if [ "${comp_dir}" = "1" ] && [ -d "${f}" ];then
-			compress
-		fi
-		if [ "${comp_files}" = "1" ] && [ -f "${f}" ];then
-			compress
-		fi
+		if [ "${comp_dir}" = "1" ] && [ -d "${f}" ];then compress;fi
+		if [ "${comp_files}" = "1" ] && [ -f "${f}" ];then compress;fi
 	done
 else
 	printf "Nothing to compress\n";exit
diff --git a/mkzip b/mkzip
--- a/mkzip
+++ b/mkzip
@@ -1,8 +1,8 @@
 #!/bin/sh
-#4.3.0
-#2018-12-30
+#5.0.0
+#2018-01-17
 
-#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
+#Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
 #
 #This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -17,56 +17,71 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-comp_files="0"
-comp_dir="0"
-orig_rm="0"
-comp_njp="0"
-test_only="0"
-test_mk7z="1"
+die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }
+test_file_list(){ if [ -f "${f%%}.zip" ];then file_list="${file_list} ${f%%}.zip";fi; }
+compress(){
+	case "${comp_type}" in
+		0)
+			nice -19 zip -rv -9 --junk-paths "${f%%}.zip" "${f%%}" || die "Compression failed for: ${f%%}"
+			test_file_list
+			;;
+		1)
+			nice -19 zip -rv -9 "${f%%}.zip" "${f%%}" || die "Compression failed for: ${f%%}"
+			test_file_list
+			;;
+		test)
+			if [ "${f##*.}" = "zip" ];then
+				case "${test_mk7z}" in
+					0) nice -19 unzip -tq "${f%%}";;
+					1) mk7z -T "${f%%}";;
+				esac
+				return
+			fi;;
+	esac
 
-compress() {
-	if [ "${comp_njp}" = "0" ] && [ "${test_only}" = "0" ];then
-		nice -19 zip -rv -9 --junk-paths "${f%%}.zip" "${f%%}"
-	elif [ "${comp_njp}" = "1" ] && [ "${test_only}" = "0" ];then
-		nice -19 zip -rv -9 "${f%%}.zip" "${f%%}"
-	fi
-
-	if [ "${test_only}" = "1" ] && ! [ "${f}" = "failed.txt" ];then
-		if [ "${test_mk7z}" = "1" ];then
-			mk7z -t "${f%%}"
+	if [ "$?" -eq 0 ] && ! [ "${comp_type}" = "test" ] && [ "${orig_rm}" = "1" ] && [ -f "${f%%}.zip" ];then
+		if [ -n "$(${0} -t "${f%%}.zip"|grep FAILED)" ];then
+			printf "Test FAILED for: ${f%%}.7z\nNot removing original: "${f%%}"\n"
 		else
-			nice -19 unzip -tq "${f%%}"
+			rm -r "${f%%}"
 		fi
-	fi
-
-	out="$?"
-	if [ "${out}" -eq 0 ] && [ "${test_only}" = "0" ] && [ "${orig_rm}" = "1" ] && [ -f "${f%%}.zip" ];then
-		rm -r "${f%%}"
 	fi
 }
 
-while getopts "TZtdfpsxzh" OPT;do
+orig_rm="0"
+comp_dir="0"
+comp_files="0"
+
+comp_type="0"
+test_post="1"
+test_mk7z="1"
+file_list=""
+
+while getopts "TZFDPRtdfszh" OPT;do
 	case "$OPT" in
-		t) test_only="1";comp_files="1";;
-		T) test_only="1";comp_files="1";test_mk7z="0";;
 		d) comp_dir="1";;
+		D) comp_dir="1";comp_type="1";;
 		f) comp_files="1";;
-		p) comp_dir="1";comp_njp="1";;
+		F) comp_files="1";orig_rm="1";;
+		P) test_post="0";;
 		s) orig_rm="1";;
-		x) comp_files="1";orig_rm="1";;
+		R) orig_rm="1";test_post="0";;
+		t) comp_type="test";;
+		T) comp_type="test";test_mk7z="0";;
 		z) comp_dir="1";orig_rm="1";;
-		Z) comp_dir="1";orig_rm="1";comp_njp="1";;
+		Z) comp_dir="1";orig_rm="1";comp_type="1";;
 		h)
-			printf " -d\tcompress all directories\n"
+			printf " -d\tcompress all directories, junk path\n"
+			printf " -D\tcompress all directories, dont junk path\n"
 			printf " -f\tcompress all files\n"
+			printf " -F\tcompress all files, delete original after compressed\n"
 			printf " -h\tprint this help\n"
-			printf " -p\tcompress all directories, dont junk path\n"
 			printf " -P\tDisable post compression test\n"
 			printf " -s\tcompress \$1, delete after compressed\n"
+			printf " -R\tdelete after compressed, will test before deleting, disables post testing, works in all modes but test\n"
 			printf " -t\tTest all files or files passed in \$1, using mk7z -t : prefered test method\n"
 			printf " -T\tTest all files or files passed in \$1, using unzip -tq\n"
-			printf " -x\tcompress all files, delete original after compressed\n"
-			printf " -z\tcompress all directories, delete original after compressed\n"
+			printf " -z\tcompress all directories, delete original after compressed, junk path\n"
 			printf " -Z\tcompress all directories, delete original after compressed, dont junk path\n"
 			exit;;
 	esac
@@ -85,13 +100,18 @@ if [ -n "${1}" ];then
 	done
 elif [ "${comp_dir}" = "1" ] || [ "${comp_files}" = "1" ];then
 	for f in *; do
-		if [ "${comp_dir}" = "1" ] && [ -d "${f%%}" ];then
-			compress
-		fi
-		if [ "${comp_files}" = "1" ] && [ -f "${f%%}" ];then
-			compress
-		fi
+		if [ "${comp_dir}" = "1" ] && [ -d "${f%%}" ];then compress;fi
+		if [ "${comp_files}" = "1" ] && [ -f "${f%%}" ];then compress;fi
 	done
 else
 	printf "Nothing to compress\n";exit
+fi
+
+if [ "${test_post}" = "1" ] && [ "${orig_rm}" = "0" ];then
+	for f in ${file_list}; do
+		if [ -f "${f}" ];then
+			comp_type="test"
+			compress
+		fi
+	done
 fi
